version: '3.7'

services:
    mongodb:
        build:
            context: ./mongo
            dockerfile: ./Dockerfile
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: figmaX
        ports:
            - 27017:27017
    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        ports:
            - 3001:3001
        env_file:
            - ./server/env/dev.env
        command: nodemon server.js
        depends_on:
            - mongodb
            - redis-cache
    redis-cache:
        image: redis:6.2-alpine
        ports:
            - 6379:6379
        volumes:
            - cache:/data
            - ./redis/redis.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf

volumes:
    mongo:
    cache:
