version: '3.7'

services:
    mongodb:
        build:
            context: ./mongo
            dockerfile: ./Dockerfile
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: figmaX
        ports:
            - 27017:27017

volumes:
  mongo: