name: UNIT Tests
run-name: UNIT Tests
on:
  push
jobs:
  UNIT-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: build
        working-directory: ./server
        run: npm install
      - name: run tests
        working-directory: ./server
        run: npm test
